package com.smepms.workattendance.mapper;

import com.smepms.workattendance.pojo.WorkAttendance;
import com.smepms.workattendance.pojo.WorkOvertime;
import com.smepms.workattendance.pojo.WorkOvertimeExample;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WorkOvertimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_overtime
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    int countByExample(WorkOvertimeExample example) throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_overtime
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    int deleteByExample(WorkOvertimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_overtime
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    int deleteByPrimaryKey(Integer workOvertimeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_overtime
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    int insert(WorkOvertime record) throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_overtime
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    int insertSelective(WorkOvertime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_overtime
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    List<WorkOvertime> selectByExample(WorkOvertimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_overtime
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    WorkOvertime selectByPrimaryKey(Integer workOvertimeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_overtime
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    int updateByExampleSelective(@Param("record") WorkOvertime record, @Param("example") WorkOvertimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_overtime
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    int updateByExample(@Param("record") WorkOvertime record, @Param("example") WorkOvertimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_overtime
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    int updateByPrimaryKeySelective(WorkOvertime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_overtime
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    int updateByPrimaryKey(WorkOvertime record);

    List<WorkOvertime> queryWorkAttendanceByEmployeeId(@Param("employeeId") Integer employeeId) throws Exception;

    List<WorkOvertime> queryWorkOvertimeByEmployeeIdListAndStatus(@Param("employeeIdList") List<Integer> employeeIdList,@Param("status") Integer status) throws Exception;

    List<WorkOvertime> selectByDate(@Param("startDate")Date startDate,@Param("endDate")Date endDate,@Param("status")Integer workOvertimeStatus) throws Exception;
}