package com.smepms.jobmanagement.mapper;

import com.smepms.jobmanagement.pojo.Function;
import com.smepms.jobmanagement.pojo.FunctionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FunctionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_function
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    int countByExample(FunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_function
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    int deleteByExample(FunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_function
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    int deleteByPrimaryKey(Integer functionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_function
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    int insert(Function record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_function
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    int insertSelective(Function record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_function
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    List<Function> selectByExample(FunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_function
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    Function selectByPrimaryKey(Integer functionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_function
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    int updateByExampleSelective(@Param("record") Function record, @Param("example") FunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_function
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    int updateByExample(@Param("record") Function record, @Param("example") FunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_function
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    int updateByPrimaryKeySelective(Function record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_function
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    int updateByPrimaryKey(Function record);
}