package com.smepms.jobmanagement.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DepartmentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_department
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_department
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_department
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public DepartmentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_department
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDepartmentIdIsNull() {
            addCriterion("department_id is null");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdIsNotNull() {
            addCriterion("department_id is not null");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdEqualTo(Integer value) {
            addCriterion("department_id =", value, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdNotEqualTo(Integer value) {
            addCriterion("department_id <>", value, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdGreaterThan(Integer value) {
            addCriterion("department_id >", value, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("department_id >=", value, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdLessThan(Integer value) {
            addCriterion("department_id <", value, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdLessThanOrEqualTo(Integer value) {
            addCriterion("department_id <=", value, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdIn(List<Integer> values) {
            addCriterion("department_id in", values, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdNotIn(List<Integer> values) {
            addCriterion("department_id not in", values, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdBetween(Integer value1, Integer value2) {
            addCriterion("department_id between", value1, value2, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("department_id not between", value1, value2, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameIsNull() {
            addCriterion("department_name is null");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameIsNotNull() {
            addCriterion("department_name is not null");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameEqualTo(String value) {
            addCriterion("department_name =", value, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameNotEqualTo(String value) {
            addCriterion("department_name <>", value, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameGreaterThan(String value) {
            addCriterion("department_name >", value, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameGreaterThanOrEqualTo(String value) {
            addCriterion("department_name >=", value, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameLessThan(String value) {
            addCriterion("department_name <", value, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameLessThanOrEqualTo(String value) {
            addCriterion("department_name <=", value, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameLike(String value) {
            addCriterion("department_name like", value, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameNotLike(String value) {
            addCriterion("department_name not like", value, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameIn(List<String> values) {
            addCriterion("department_name in", values, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameNotIn(List<String> values) {
            addCriterion("department_name not in", values, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameBetween(String value1, String value2) {
            addCriterion("department_name between", value1, value2, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameNotBetween(String value1, String value2) {
            addCriterion("department_name not between", value1, value2, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentCreaterIsNull() {
            addCriterion("department_creater is null");
            return (Criteria) this;
        }

        public Criteria andDepartmentCreaterIsNotNull() {
            addCriterion("department_creater is not null");
            return (Criteria) this;
        }

        public Criteria andDepartmentCreaterEqualTo(Integer value) {
            addCriterion("department_creater =", value, "departmentCreater");
            return (Criteria) this;
        }

        public Criteria andDepartmentCreaterNotEqualTo(Integer value) {
            addCriterion("department_creater <>", value, "departmentCreater");
            return (Criteria) this;
        }

        public Criteria andDepartmentCreaterGreaterThan(Integer value) {
            addCriterion("department_creater >", value, "departmentCreater");
            return (Criteria) this;
        }

        public Criteria andDepartmentCreaterGreaterThanOrEqualTo(Integer value) {
            addCriterion("department_creater >=", value, "departmentCreater");
            return (Criteria) this;
        }

        public Criteria andDepartmentCreaterLessThan(Integer value) {
            addCriterion("department_creater <", value, "departmentCreater");
            return (Criteria) this;
        }

        public Criteria andDepartmentCreaterLessThanOrEqualTo(Integer value) {
            addCriterion("department_creater <=", value, "departmentCreater");
            return (Criteria) this;
        }

        public Criteria andDepartmentCreaterIn(List<Integer> values) {
            addCriterion("department_creater in", values, "departmentCreater");
            return (Criteria) this;
        }

        public Criteria andDepartmentCreaterNotIn(List<Integer> values) {
            addCriterion("department_creater not in", values, "departmentCreater");
            return (Criteria) this;
        }

        public Criteria andDepartmentCreaterBetween(Integer value1, Integer value2) {
            addCriterion("department_creater between", value1, value2, "departmentCreater");
            return (Criteria) this;
        }

        public Criteria andDepartmentCreaterNotBetween(Integer value1, Integer value2) {
            addCriterion("department_creater not between", value1, value2, "departmentCreater");
            return (Criteria) this;
        }

        public Criteria andDepartmentSignIsNull() {
            addCriterion("department_sign is null");
            return (Criteria) this;
        }

        public Criteria andDepartmentSignIsNotNull() {
            addCriterion("department_sign is not null");
            return (Criteria) this;
        }

        public Criteria andDepartmentSignEqualTo(String value) {
            addCriterion("department_sign =", value, "departmentSign");
            return (Criteria) this;
        }

        public Criteria andDepartmentSignNotEqualTo(String value) {
            addCriterion("department_sign <>", value, "departmentSign");
            return (Criteria) this;
        }

        public Criteria andDepartmentSignGreaterThan(String value) {
            addCriterion("department_sign >", value, "departmentSign");
            return (Criteria) this;
        }

        public Criteria andDepartmentSignGreaterThanOrEqualTo(String value) {
            addCriterion("department_sign >=", value, "departmentSign");
            return (Criteria) this;
        }

        public Criteria andDepartmentSignLessThan(String value) {
            addCriterion("department_sign <", value, "departmentSign");
            return (Criteria) this;
        }

        public Criteria andDepartmentSignLessThanOrEqualTo(String value) {
            addCriterion("department_sign <=", value, "departmentSign");
            return (Criteria) this;
        }

        public Criteria andDepartmentSignLike(String value) {
            addCriterion("department_sign like", value, "departmentSign");
            return (Criteria) this;
        }

        public Criteria andDepartmentSignNotLike(String value) {
            addCriterion("department_sign not like", value, "departmentSign");
            return (Criteria) this;
        }

        public Criteria andDepartmentSignIn(List<String> values) {
            addCriterion("department_sign in", values, "departmentSign");
            return (Criteria) this;
        }

        public Criteria andDepartmentSignNotIn(List<String> values) {
            addCriterion("department_sign not in", values, "departmentSign");
            return (Criteria) this;
        }

        public Criteria andDepartmentSignBetween(String value1, String value2) {
            addCriterion("department_sign between", value1, value2, "departmentSign");
            return (Criteria) this;
        }

        public Criteria andDepartmentSignNotBetween(String value1, String value2) {
            addCriterion("department_sign not between", value1, value2, "departmentSign");
            return (Criteria) this;
        }

        public Criteria andDepartmentCreateTimeIsNull() {
            addCriterion("department_create_time is null");
            return (Criteria) this;
        }

        public Criteria andDepartmentCreateTimeIsNotNull() {
            addCriterion("department_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andDepartmentCreateTimeEqualTo(Date value) {
            addCriterion("department_create_time =", value, "departmentCreateTime");
            return (Criteria) this;
        }

        public Criteria andDepartmentCreateTimeNotEqualTo(Date value) {
            addCriterion("department_create_time <>", value, "departmentCreateTime");
            return (Criteria) this;
        }

        public Criteria andDepartmentCreateTimeGreaterThan(Date value) {
            addCriterion("department_create_time >", value, "departmentCreateTime");
            return (Criteria) this;
        }

        public Criteria andDepartmentCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("department_create_time >=", value, "departmentCreateTime");
            return (Criteria) this;
        }

        public Criteria andDepartmentCreateTimeLessThan(Date value) {
            addCriterion("department_create_time <", value, "departmentCreateTime");
            return (Criteria) this;
        }

        public Criteria andDepartmentCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("department_create_time <=", value, "departmentCreateTime");
            return (Criteria) this;
        }

        public Criteria andDepartmentCreateTimeIn(List<Date> values) {
            addCriterion("department_create_time in", values, "departmentCreateTime");
            return (Criteria) this;
        }

        public Criteria andDepartmentCreateTimeNotIn(List<Date> values) {
            addCriterion("department_create_time not in", values, "departmentCreateTime");
            return (Criteria) this;
        }

        public Criteria andDepartmentCreateTimeBetween(Date value1, Date value2) {
            addCriterion("department_create_time between", value1, value2, "departmentCreateTime");
            return (Criteria) this;
        }

        public Criteria andDepartmentCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("department_create_time not between", value1, value2, "departmentCreateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_department
     *
     * @mbggenerated do_not_delete_during_merge Wed Jan 10 18:43:08 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_department
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}