package com.smepms.jobmanagement.pojo;

public class EmployeeWithBLOBs extends Employee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.employee_introduction
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    private String employeeIntroduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.employee_head_sculpture
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    private String employeeHeadSculpture;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.employee_introduction
     *
     * @return the value of t_employee.employee_introduction
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public String getEmployeeIntroduction() {
        return employeeIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.employee_introduction
     *
     * @param employeeIntroduction the value for t_employee.employee_introduction
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void setEmployeeIntroduction(String employeeIntroduction) {
        this.employeeIntroduction = employeeIntroduction == null ? null : employeeIntroduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.employee_head_sculpture
     *
     * @return the value of t_employee.employee_head_sculpture
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public String getEmployeeHeadSculpture() {
        return employeeHeadSculpture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.employee_head_sculpture
     *
     * @param employeeHeadSculpture the value for t_employee.employee_head_sculpture
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void setEmployeeHeadSculpture(String employeeHeadSculpture) {
        this.employeeHeadSculpture = employeeHeadSculpture == null ? null : employeeHeadSculpture.trim();
    }




}