package com.smepms.jobmanagement.pojo;

import java.io.Serializable;
import java.util.Date;

public class Employee implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.employee_id
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    private Integer employeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.status_id
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    private Integer statusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.employee_name
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    private String employeeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.employee_password
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    private String employeePassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.employee_phone
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    private String employeePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.employee_email
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    private String employeeEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.employee_birthday
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    private Date employeeBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.employee_create_time
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    private Date employeeCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.employee_work_id
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    private Integer employeeWorkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.employee_leader
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    private Integer employeeLeader;

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Employee)) return false;

        Employee employee = (Employee) o;

        return employeeId != null ? employeeId.equals(employee.employeeId) : employee.employeeId == null;
    }

    @Override
    public int hashCode() {
        return employeeId != null ? employeeId.hashCode() : 0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.employee_id
     *
     * @return the value of t_employee.employee_id
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */




//    以下为自己添加的属性

    private Department department;

    private Position position;

    private String employeeLeaderName;

    private Integer employeeLeaderId;

    private Integer employeeLeaderWorkId;

    public String getEmployeeLeaderName() {
        return employeeLeaderName;
    }

    public void setEmployeeLeaderName(String employeeLeaderName) {
        this.employeeLeaderName = employeeLeaderName;
    }

    public Integer getEmployeeLeaderId() {
        return employeeLeaderId;
    }

    public void setEmployeeLeaderId(Integer employeeLeaderId) {
        this.employeeLeaderId = employeeLeaderId;
    }

    public Department getDepartment() {
        return department;
    }

    public void setDepartment(Department department) {
        this.department = department;
    }

    public Position getPosition() {
        return position;
    }

    public void setPosition(Position position) {
        this.position = position;
    }

    public Integer getEmployeeId() {
        return employeeId;
    }

    public Integer getEmployeeLeaderWorkId() {
        return employeeLeaderWorkId;
    }

    public void setEmployeeLeaderWorkId(Integer employeeLeaderWorkId) {
        this.employeeLeaderWorkId = employeeLeaderWorkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.employee_id
     *
     * @param employeeId the value for t_employee.employee_id
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.status_id
     *
     * @return the value of t_employee.status_id
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public Integer getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.status_id
     *
     * @param statusId the value for t_employee.status_id
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.employee_name
     *
     * @return the value of t_employee.employee_name
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public String getEmployeeName() {
        return employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.employee_name
     *
     * @param employeeName the value for t_employee.employee_name
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName == null ? null : employeeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.employee_password
     *
     * @return the value of t_employee.employee_password
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public String getEmployeePassword() {
        return employeePassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.employee_password
     *
     * @param employeePassword the value for t_employee.employee_password
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void setEmployeePassword(String employeePassword) {
        this.employeePassword = employeePassword == null ? null : employeePassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.employee_phone
     *
     * @return the value of t_employee.employee_phone
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public String getEmployeePhone() {
        return employeePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.employee_phone
     *
     * @param employeePhone the value for t_employee.employee_phone
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void setEmployeePhone(String employeePhone) {
        this.employeePhone = employeePhone == null ? null : employeePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.employee_email
     *
     * @return the value of t_employee.employee_email
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public String getEmployeeEmail() {
        return employeeEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.employee_email
     *
     * @param employeeEmail the value for t_employee.employee_email
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void setEmployeeEmail(String employeeEmail) {
        this.employeeEmail = employeeEmail == null ? null : employeeEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.employee_birthday
     *
     * @return the value of t_employee.employee_birthday
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public Date getEmployeeBirthday() {
        return employeeBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.employee_birthday
     *
     * @param employeeBirthday the value for t_employee.employee_birthday
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void setEmployeeBirthday(Date employeeBirthday) {
        this.employeeBirthday = employeeBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.employee_create_time
     *
     * @return the value of t_employee.employee_create_time
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public Date getEmployeeCreateTime() {
        return employeeCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.employee_create_time
     *
     * @param employeeCreateTime the value for t_employee.employee_create_time
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void setEmployeeCreateTime(Date employeeCreateTime) {
        this.employeeCreateTime = employeeCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.employee_work_id
     *
     * @return the value of t_employee.employee_work_id
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public Integer getEmployeeWorkId() {
        return employeeWorkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.employee_work_id
     *
     * @param employeeWorkId the value for t_employee.employee_work_id
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void setEmployeeWorkId(Integer employeeWorkId) {
        this.employeeWorkId = employeeWorkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.employee_leader
     *
     * @return the value of t_employee.employee_leader
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public Integer getEmployeeLeader() {
        return employeeLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.employee_leader
     *
     * @param employeeLeader the value for t_employee.employee_leader
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void setEmployeeLeader(Integer employeeLeader) {
        this.employeeLeader = employeeLeader;
    }
}