package com.smepms.jobmanagement.pojo;

public class Function {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_function.function_id
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    private Integer functionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_function.function_name
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    private String functionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_function.function_icon_url
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    private String functionIconUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_function.function_url
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    private String functionUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_function.function_id
     *
     * @return the value of t_function.function_id
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public Integer getFunctionId() {
        return functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_function.function_id
     *
     * @param functionId the value for t_function.function_id
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void setFunctionId(Integer functionId) {
        this.functionId = functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_function.function_name
     *
     * @return the value of t_function.function_name
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public String getFunctionName() {
        return functionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_function.function_name
     *
     * @param functionName the value for t_function.function_name
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void setFunctionName(String functionName) {
        this.functionName = functionName == null ? null : functionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_function.function_icon_url
     *
     * @return the value of t_function.function_icon_url
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public String getFunctionIconUrl() {
        return functionIconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_function.function_icon_url
     *
     * @param functionIconUrl the value for t_function.function_icon_url
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void setFunctionIconUrl(String functionIconUrl) {
        this.functionIconUrl = functionIconUrl == null ? null : functionIconUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_function.function_url
     *
     * @return the value of t_function.function_url
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public String getFunctionUrl() {
        return functionUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_function.function_url
     *
     * @param functionUrl the value for t_function.function_url
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void setFunctionUrl(String functionUrl) {
        this.functionUrl = functionUrl == null ? null : functionUrl.trim();
    }
}