package com.smepms.jobmanagement.pojo;

public class Status {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_status.status_id
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    private Integer statusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_status.status_name
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    private String statusName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_status.status_id
     *
     * @return the value of t_status.status_id
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public Integer getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_status.status_id
     *
     * @param statusId the value for t_status.status_id
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_status.status_name
     *
     * @return the value of t_status.status_name
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public String getStatusName() {
        return statusName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_status.status_name
     *
     * @param statusName the value for t_status.status_name
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void setStatusName(String statusName) {
        this.statusName = statusName == null ? null : statusName.trim();
    }
}