package com.smepms.salaryconfig.mapper;

import com.smepms.salaryconfig.pojo.SalaryContext;
import com.smepms.salaryconfig.pojo.SalaryContextExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SalaryContextMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_attendance
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    int countByExample(SalaryContextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_attendance
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    int deleteByExample(SalaryContextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_attendance
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    int deleteByPrimaryKey(Integer workAttendanceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_attendance
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    int insert(SalaryContext record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_attendance
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    int insertSelective(SalaryContext record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_attendance
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    List<SalaryContext> selectByExample(SalaryContextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_attendance
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    SalaryContext selectByPrimaryKey(Integer workAttendanceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_attendance
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    int updateByExampleSelective(@Param("record") SalaryContext record, @Param("example") SalaryContextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_attendance
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    int updateByExample(@Param("record") SalaryContext record, @Param("example") SalaryContextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_attendance
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    int updateByPrimaryKeySelective(SalaryContext record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_attendance
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    int updateByPrimaryKey(SalaryContext record);
}