package com.smepms.workattendance.pojo;

import com.smepms.jobmanagement.pojo.Employee;

import java.util.Date;

public class WorkOvertime {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_work_overtime.work_overtime_id
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    private Integer workOvertimeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_work_overtime.work_overtime_date
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    private Date workOvertimeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_work_overtime.work_overtime_hour
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    private Integer workOvertimeHour;

    private WorkOverTimeStatus workOverTimeStatus;

    public WorkOverTimeStatus getWorkOverTimeStatus() {
        return workOverTimeStatus;
    }

    public void setWorkOverTimeStatus(WorkOverTimeStatus workOverTimeStatus) {
        this.workOverTimeStatus = workOverTimeStatus;
    }

    private Employee employee;

    public Employee getEmployee() {
        return employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_work_overtime.work_overtime_id
     *
     * @return the value of t_work_overtime.work_overtime_id
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public Integer getWorkOvertimeId() {
        return workOvertimeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_work_overtime.work_overtime_id
     *
     * @param workOvertimeId the value for t_work_overtime.work_overtime_id
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void setWorkOvertimeId(Integer workOvertimeId) {
        this.workOvertimeId = workOvertimeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_work_overtime.work_overtime_date
     *
     * @return the value of t_work_overtime.work_overtime_date
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public Date getWorkOvertimeDate() {
        return workOvertimeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_work_overtime.work_overtime_date
     *
     * @param workOvertimeDate the value for t_work_overtime.work_overtime_date
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void setWorkOvertimeDate(Date workOvertimeDate) {
        this.workOvertimeDate = workOvertimeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_work_overtime.work_overtime_hour
     *
     * @return the value of t_work_overtime.work_overtime_hour
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public Integer getWorkOvertimeHour() {
        return workOvertimeHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_work_overtime.work_overtime_hour
     *
     * @param workOvertimeHour the value for t_work_overtime.work_overtime_hour
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void setWorkOvertimeHour(Integer workOvertimeHour) {
        this.workOvertimeHour = workOvertimeHour;
    }
}