package com.smepms.workattendance.pojo;

import com.smepms.jobmanagement.pojo.Employee;

import java.util.Date;

public class WorkAttendance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_work_attendance.work_attendance_id
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    private Integer workAttendanceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_work_attendance.work_overtime_id
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    private Integer workOvertimeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_work_attendance.employee_id
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    private Integer employeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_work_attendance.work_attendance_date
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    private Date workAttendanceDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_work_attendance.late
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    private Integer late;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_work_attendance.leave_early
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    private Integer leaveEarly;

    private Employee employee;

    public Employee getEmployee() {
        return employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    private WorkAttendanceCheck workAttendanceCheck;

    public WorkAttendanceCheck getWorkAttendanceCheck() {
        return workAttendanceCheck;
    }

    public void setWorkAttendanceCheck(WorkAttendanceCheck workAttendanceCheck) {
        this.workAttendanceCheck = workAttendanceCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_work_attendance.work_attendance_id
     *
     * @return the value of t_work_attendance.work_attendance_id
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public Integer getWorkAttendanceId() {
        return workAttendanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_work_attendance.work_attendance_id
     *
     * @param workAttendanceId the value for t_work_attendance.work_attendance_id
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void setWorkAttendanceId(Integer workAttendanceId) {
        this.workAttendanceId = workAttendanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_work_attendance.work_overtime_id
     *
     * @return the value of t_work_attendance.work_overtime_id
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public Integer getWorkOvertimeId() {
        return workOvertimeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_work_attendance.work_overtime_id
     *
     * @param workOvertimeId the value for t_work_attendance.work_overtime_id
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void setWorkOvertimeId(Integer workOvertimeId) {
        this.workOvertimeId = workOvertimeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_work_attendance.employee_id
     *
     * @return the value of t_work_attendance.employee_id
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_work_attendance.employee_id
     *
     * @param employeeId the value for t_work_attendance.employee_id
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_work_attendance.work_attendance_date
     *
     * @return the value of t_work_attendance.work_attendance_date
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public Date getWorkAttendanceDate() {
        return workAttendanceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_work_attendance.work_attendance_date
     *
     * @param workAttendanceDate the value for t_work_attendance.work_attendance_date
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void setWorkAttendanceDate(Date workAttendanceDate) {
        this.workAttendanceDate = workAttendanceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_work_attendance.late
     *
     * @return the value of t_work_attendance.late
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public Integer getLate() {
        return late;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_work_attendance.late
     *
     * @param late the value for t_work_attendance.late
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void setLate(Integer late) {
        this.late = late;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_work_attendance.leave_early
     *
     * @return the value of t_work_attendance.leave_early
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public Integer getLeaveEarly() {
        return leaveEarly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_work_attendance.leave_early
     *
     * @param leaveEarly the value for t_work_attendance.leave_early
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void setLeaveEarly(Integer leaveEarly) {
        this.leaveEarly = leaveEarly;
    }
}