package com.smepms.workattendance.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class WorkOvertimeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_work_overtime
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_work_overtime
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_work_overtime
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_overtime
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public WorkOvertimeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_overtime
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_overtime
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_overtime
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_overtime
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_overtime
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_overtime
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_overtime
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_overtime
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_overtime
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_overtime
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_work_overtime
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andWorkOvertimeIdIsNull() {
            addCriterion("work_overtime_id is null");
            return (Criteria) this;
        }

        public Criteria andWorkOvertimeIdIsNotNull() {
            addCriterion("work_overtime_id is not null");
            return (Criteria) this;
        }

        public Criteria andWorkOvertimeIdEqualTo(Integer value) {
            addCriterion("work_overtime_id =", value, "workOvertimeId");
            return (Criteria) this;
        }

        public Criteria andWorkOvertimeIdNotEqualTo(Integer value) {
            addCriterion("work_overtime_id <>", value, "workOvertimeId");
            return (Criteria) this;
        }

        public Criteria andWorkOvertimeIdGreaterThan(Integer value) {
            addCriterion("work_overtime_id >", value, "workOvertimeId");
            return (Criteria) this;
        }

        public Criteria andWorkOvertimeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("work_overtime_id >=", value, "workOvertimeId");
            return (Criteria) this;
        }

        public Criteria andWorkOvertimeIdLessThan(Integer value) {
            addCriterion("work_overtime_id <", value, "workOvertimeId");
            return (Criteria) this;
        }

        public Criteria andWorkOvertimeIdLessThanOrEqualTo(Integer value) {
            addCriterion("work_overtime_id <=", value, "workOvertimeId");
            return (Criteria) this;
        }

        public Criteria andWorkOvertimeIdIn(List<Integer> values) {
            addCriterion("work_overtime_id in", values, "workOvertimeId");
            return (Criteria) this;
        }

        public Criteria andWorkOvertimeIdNotIn(List<Integer> values) {
            addCriterion("work_overtime_id not in", values, "workOvertimeId");
            return (Criteria) this;
        }

        public Criteria andWorkOvertimeIdBetween(Integer value1, Integer value2) {
            addCriterion("work_overtime_id between", value1, value2, "workOvertimeId");
            return (Criteria) this;
        }

        public Criteria andWorkOvertimeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("work_overtime_id not between", value1, value2, "workOvertimeId");
            return (Criteria) this;
        }

        public Criteria andWorkOvertimeDateIsNull() {
            addCriterion("work_overtime_date is null");
            return (Criteria) this;
        }

        public Criteria andWorkOvertimeDateIsNotNull() {
            addCriterion("work_overtime_date is not null");
            return (Criteria) this;
        }

        public Criteria andWorkOvertimeDateEqualTo(Date value) {
            addCriterionForJDBCDate("work_overtime_date =", value, "workOvertimeDate");
            return (Criteria) this;
        }

        public Criteria andWorkOvertimeDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("work_overtime_date <>", value, "workOvertimeDate");
            return (Criteria) this;
        }

        public Criteria andWorkOvertimeDateGreaterThan(Date value) {
            addCriterionForJDBCDate("work_overtime_date >", value, "workOvertimeDate");
            return (Criteria) this;
        }

        public Criteria andWorkOvertimeDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("work_overtime_date >=", value, "workOvertimeDate");
            return (Criteria) this;
        }

        public Criteria andWorkOvertimeDateLessThan(Date value) {
            addCriterionForJDBCDate("work_overtime_date <", value, "workOvertimeDate");
            return (Criteria) this;
        }

        public Criteria andWorkOvertimeDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("work_overtime_date <=", value, "workOvertimeDate");
            return (Criteria) this;
        }

        public Criteria andWorkOvertimeDateIn(List<Date> values) {
            addCriterionForJDBCDate("work_overtime_date in", values, "workOvertimeDate");
            return (Criteria) this;
        }

        public Criteria andWorkOvertimeDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("work_overtime_date not in", values, "workOvertimeDate");
            return (Criteria) this;
        }

        public Criteria andWorkOvertimeDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("work_overtime_date between", value1, value2, "workOvertimeDate");
            return (Criteria) this;
        }

        public Criteria andWorkOvertimeDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("work_overtime_date not between", value1, value2, "workOvertimeDate");
            return (Criteria) this;
        }

        public Criteria andWorkOvertimeHourIsNull() {
            addCriterion("work_overtime_hour is null");
            return (Criteria) this;
        }

        public Criteria andWorkOvertimeHourIsNotNull() {
            addCriterion("work_overtime_hour is not null");
            return (Criteria) this;
        }

        public Criteria andWorkOvertimeHourEqualTo(Integer value) {
            addCriterion("work_overtime_hour =", value, "workOvertimeHour");
            return (Criteria) this;
        }

        public Criteria andWorkOvertimeHourNotEqualTo(Integer value) {
            addCriterion("work_overtime_hour <>", value, "workOvertimeHour");
            return (Criteria) this;
        }

        public Criteria andWorkOvertimeHourGreaterThan(Integer value) {
            addCriterion("work_overtime_hour >", value, "workOvertimeHour");
            return (Criteria) this;
        }

        public Criteria andWorkOvertimeHourGreaterThanOrEqualTo(Integer value) {
            addCriterion("work_overtime_hour >=", value, "workOvertimeHour");
            return (Criteria) this;
        }

        public Criteria andWorkOvertimeHourLessThan(Integer value) {
            addCriterion("work_overtime_hour <", value, "workOvertimeHour");
            return (Criteria) this;
        }

        public Criteria andWorkOvertimeHourLessThanOrEqualTo(Integer value) {
            addCriterion("work_overtime_hour <=", value, "workOvertimeHour");
            return (Criteria) this;
        }

        public Criteria andWorkOvertimeHourIn(List<Integer> values) {
            addCriterion("work_overtime_hour in", values, "workOvertimeHour");
            return (Criteria) this;
        }

        public Criteria andWorkOvertimeHourNotIn(List<Integer> values) {
            addCriterion("work_overtime_hour not in", values, "workOvertimeHour");
            return (Criteria) this;
        }

        public Criteria andWorkOvertimeHourBetween(Integer value1, Integer value2) {
            addCriterion("work_overtime_hour between", value1, value2, "workOvertimeHour");
            return (Criteria) this;
        }

        public Criteria andWorkOvertimeHourNotBetween(Integer value1, Integer value2) {
            addCriterion("work_overtime_hour not between", value1, value2, "workOvertimeHour");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_work_overtime
     *
     * @mbggenerated do_not_delete_during_merge Wed Jan 10 18:43:08 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_work_overtime
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}