package com.smepms.salaryconfig.pojo;

import java.util.ArrayList;
import java.util.List;

public class EmployeeSalaryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_employee_salary
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_employee_salary
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_employee_salary
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employee_salary
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public EmployeeSalaryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employee_salary
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employee_salary
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employee_salary
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employee_salary
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employee_salary
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employee_salary
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employee_salary
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employee_salary
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employee_salary
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employee_salary
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_employee_salary
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEmployeeSalaryIdIsNull() {
            addCriterion("employee_salary_id is null");
            return (Criteria) this;
        }

        public Criteria andEmployeeSalaryIdIsNotNull() {
            addCriterion("employee_salary_id is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeeSalaryIdEqualTo(Integer value) {
            addCriterion("employee_salary_id =", value, "employeeSalaryId");
            return (Criteria) this;
        }

        public Criteria andEmployeeSalaryIdNotEqualTo(Integer value) {
            addCriterion("employee_salary_id <>", value, "employeeSalaryId");
            return (Criteria) this;
        }

        public Criteria andEmployeeSalaryIdGreaterThan(Integer value) {
            addCriterion("employee_salary_id >", value, "employeeSalaryId");
            return (Criteria) this;
        }

        public Criteria andEmployeeSalaryIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("employee_salary_id >=", value, "employeeSalaryId");
            return (Criteria) this;
        }

        public Criteria andEmployeeSalaryIdLessThan(Integer value) {
            addCriterion("employee_salary_id <", value, "employeeSalaryId");
            return (Criteria) this;
        }

        public Criteria andEmployeeSalaryIdLessThanOrEqualTo(Integer value) {
            addCriterion("employee_salary_id <=", value, "employeeSalaryId");
            return (Criteria) this;
        }

        public Criteria andEmployeeSalaryIdIn(List<Integer> values) {
            addCriterion("employee_salary_id in", values, "employeeSalaryId");
            return (Criteria) this;
        }

        public Criteria andEmployeeSalaryIdNotIn(List<Integer> values) {
            addCriterion("employee_salary_id not in", values, "employeeSalaryId");
            return (Criteria) this;
        }

        public Criteria andEmployeeSalaryIdBetween(Integer value1, Integer value2) {
            addCriterion("employee_salary_id between", value1, value2, "employeeSalaryId");
            return (Criteria) this;
        }

        public Criteria andEmployeeSalaryIdNotBetween(Integer value1, Integer value2) {
            addCriterion("employee_salary_id not between", value1, value2, "employeeSalaryId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdIsNull() {
            addCriterion("employee_id is null");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdIsNotNull() {
            addCriterion("employee_id is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdEqualTo(Integer value) {
            addCriterion("employee_id =", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdNotEqualTo(Integer value) {
            addCriterion("employee_id <>", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdGreaterThan(Integer value) {
            addCriterion("employee_id >", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("employee_id >=", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdLessThan(Integer value) {
            addCriterion("employee_id <", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdLessThanOrEqualTo(Integer value) {
            addCriterion("employee_id <=", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdIn(List<Integer> values) {
            addCriterion("employee_id in", values, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdNotIn(List<Integer> values) {
            addCriterion("employee_id not in", values, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdBetween(Integer value1, Integer value2) {
            addCriterion("employee_id between", value1, value2, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("employee_id not between", value1, value2, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeSalaryTotalIsNull() {
            addCriterion("employee_salary_total is null");
            return (Criteria) this;
        }

        public Criteria andEmployeeSalaryTotalIsNotNull() {
            addCriterion("employee_salary_total is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeeSalaryTotalEqualTo(Float value) {
            addCriterion("employee_salary_total =", value, "employeeSalaryTotal");
            return (Criteria) this;
        }

        public Criteria andEmployeeSalaryTotalNotEqualTo(Float value) {
            addCriterion("employee_salary_total <>", value, "employeeSalaryTotal");
            return (Criteria) this;
        }

        public Criteria andEmployeeSalaryTotalGreaterThan(Float value) {
            addCriterion("employee_salary_total >", value, "employeeSalaryTotal");
            return (Criteria) this;
        }

        public Criteria andEmployeeSalaryTotalGreaterThanOrEqualTo(Float value) {
            addCriterion("employee_salary_total >=", value, "employeeSalaryTotal");
            return (Criteria) this;
        }

        public Criteria andEmployeeSalaryTotalLessThan(Float value) {
            addCriterion("employee_salary_total <", value, "employeeSalaryTotal");
            return (Criteria) this;
        }

        public Criteria andEmployeeSalaryTotalLessThanOrEqualTo(Float value) {
            addCriterion("employee_salary_total <=", value, "employeeSalaryTotal");
            return (Criteria) this;
        }

        public Criteria andEmployeeSalaryTotalIn(List<Float> values) {
            addCriterion("employee_salary_total in", values, "employeeSalaryTotal");
            return (Criteria) this;
        }

        public Criteria andEmployeeSalaryTotalNotIn(List<Float> values) {
            addCriterion("employee_salary_total not in", values, "employeeSalaryTotal");
            return (Criteria) this;
        }

        public Criteria andEmployeeSalaryTotalBetween(Float value1, Float value2) {
            addCriterion("employee_salary_total between", value1, value2, "employeeSalaryTotal");
            return (Criteria) this;
        }

        public Criteria andEmployeeSalaryTotalNotBetween(Float value1, Float value2) {
            addCriterion("employee_salary_total not between", value1, value2, "employeeSalaryTotal");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_employee_salary
     *
     * @mbggenerated do_not_delete_during_merge Wed Jan 10 18:43:08 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_employee_salary
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}