package com.smepms.salaryconfig.pojo;

public class EmployeeSalary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee_salary.employee_salary_id
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    private Integer employeeSalaryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee_salary.employee_id
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    private Integer employeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee_salary.employee_salary_total
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    private Float employeeSalaryTotal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee_salary.employee_salary_id
     *
     * @return the value of t_employee_salary.employee_salary_id
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public Integer getEmployeeSalaryId() {
        return employeeSalaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee_salary.employee_salary_id
     *
     * @param employeeSalaryId the value for t_employee_salary.employee_salary_id
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void setEmployeeSalaryId(Integer employeeSalaryId) {
        this.employeeSalaryId = employeeSalaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee_salary.employee_id
     *
     * @return the value of t_employee_salary.employee_id
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee_salary.employee_id
     *
     * @param employeeId the value for t_employee_salary.employee_id
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee_salary.employee_salary_total
     *
     * @return the value of t_employee_salary.employee_salary_total
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public Float getEmployeeSalaryTotal() {
        return employeeSalaryTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee_salary.employee_salary_total
     *
     * @param employeeSalaryTotal the value for t_employee_salary.employee_salary_total
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void setEmployeeSalaryTotal(Float employeeSalaryTotal) {
        this.employeeSalaryTotal = employeeSalaryTotal;
    }
}