package com.smepms.salaryconfig.pojo;

public class Performance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_performance.performance_id
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    private Integer performanceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_performance.performance_name
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    private String performanceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_performance.performance_salary
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    private Float performanceSalary;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_performance.performance_id
     *
     * @return the value of t_performance.performance_id
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public Integer getPerformanceId() {
        return performanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_performance.performance_id
     *
     * @param performanceId the value for t_performance.performance_id
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void setPerformanceId(Integer performanceId) {
        this.performanceId = performanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_performance.performance_name
     *
     * @return the value of t_performance.performance_name
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public String getPerformanceName() {
        return performanceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_performance.performance_name
     *
     * @param performanceName the value for t_performance.performance_name
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void setPerformanceName(String performanceName) {
        this.performanceName = performanceName == null ? null : performanceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_performance.performance_salary
     *
     * @return the value of t_performance.performance_salary
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public Float getPerformanceSalary() {
        return performanceSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_performance.performance_salary
     *
     * @param performanceSalary the value for t_performance.performance_salary
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void setPerformanceSalary(Float performanceSalary) {
        this.performanceSalary = performanceSalary;
    }
}