package com.smepms.salaryconfig.pojo;

import java.util.ArrayList;
import java.util.List;

public class PerformanceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_performance
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_performance
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_performance
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_performance
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public PerformanceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_performance
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_performance
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_performance
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_performance
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_performance
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_performance
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_performance
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_performance
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_performance
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_performance
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_performance
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPerformanceIdIsNull() {
            addCriterion("performance_id is null");
            return (Criteria) this;
        }

        public Criteria andPerformanceIdIsNotNull() {
            addCriterion("performance_id is not null");
            return (Criteria) this;
        }

        public Criteria andPerformanceIdEqualTo(Integer value) {
            addCriterion("performance_id =", value, "performanceId");
            return (Criteria) this;
        }

        public Criteria andPerformanceIdNotEqualTo(Integer value) {
            addCriterion("performance_id <>", value, "performanceId");
            return (Criteria) this;
        }

        public Criteria andPerformanceIdGreaterThan(Integer value) {
            addCriterion("performance_id >", value, "performanceId");
            return (Criteria) this;
        }

        public Criteria andPerformanceIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("performance_id >=", value, "performanceId");
            return (Criteria) this;
        }

        public Criteria andPerformanceIdLessThan(Integer value) {
            addCriterion("performance_id <", value, "performanceId");
            return (Criteria) this;
        }

        public Criteria andPerformanceIdLessThanOrEqualTo(Integer value) {
            addCriterion("performance_id <=", value, "performanceId");
            return (Criteria) this;
        }

        public Criteria andPerformanceIdIn(List<Integer> values) {
            addCriterion("performance_id in", values, "performanceId");
            return (Criteria) this;
        }

        public Criteria andPerformanceIdNotIn(List<Integer> values) {
            addCriterion("performance_id not in", values, "performanceId");
            return (Criteria) this;
        }

        public Criteria andPerformanceIdBetween(Integer value1, Integer value2) {
            addCriterion("performance_id between", value1, value2, "performanceId");
            return (Criteria) this;
        }

        public Criteria andPerformanceIdNotBetween(Integer value1, Integer value2) {
            addCriterion("performance_id not between", value1, value2, "performanceId");
            return (Criteria) this;
        }

        public Criteria andPerformanceNameIsNull() {
            addCriterion("performance_name is null");
            return (Criteria) this;
        }

        public Criteria andPerformanceNameIsNotNull() {
            addCriterion("performance_name is not null");
            return (Criteria) this;
        }

        public Criteria andPerformanceNameEqualTo(String value) {
            addCriterion("performance_name =", value, "performanceName");
            return (Criteria) this;
        }

        public Criteria andPerformanceNameNotEqualTo(String value) {
            addCriterion("performance_name <>", value, "performanceName");
            return (Criteria) this;
        }

        public Criteria andPerformanceNameGreaterThan(String value) {
            addCriterion("performance_name >", value, "performanceName");
            return (Criteria) this;
        }

        public Criteria andPerformanceNameGreaterThanOrEqualTo(String value) {
            addCriterion("performance_name >=", value, "performanceName");
            return (Criteria) this;
        }

        public Criteria andPerformanceNameLessThan(String value) {
            addCriterion("performance_name <", value, "performanceName");
            return (Criteria) this;
        }

        public Criteria andPerformanceNameLessThanOrEqualTo(String value) {
            addCriterion("performance_name <=", value, "performanceName");
            return (Criteria) this;
        }

        public Criteria andPerformanceNameLike(String value) {
            addCriterion("performance_name like", value, "performanceName");
            return (Criteria) this;
        }

        public Criteria andPerformanceNameNotLike(String value) {
            addCriterion("performance_name not like", value, "performanceName");
            return (Criteria) this;
        }

        public Criteria andPerformanceNameIn(List<String> values) {
            addCriterion("performance_name in", values, "performanceName");
            return (Criteria) this;
        }

        public Criteria andPerformanceNameNotIn(List<String> values) {
            addCriterion("performance_name not in", values, "performanceName");
            return (Criteria) this;
        }

        public Criteria andPerformanceNameBetween(String value1, String value2) {
            addCriterion("performance_name between", value1, value2, "performanceName");
            return (Criteria) this;
        }

        public Criteria andPerformanceNameNotBetween(String value1, String value2) {
            addCriterion("performance_name not between", value1, value2, "performanceName");
            return (Criteria) this;
        }

        public Criteria andPerformanceSalaryIsNull() {
            addCriterion("performance_salary is null");
            return (Criteria) this;
        }

        public Criteria andPerformanceSalaryIsNotNull() {
            addCriterion("performance_salary is not null");
            return (Criteria) this;
        }

        public Criteria andPerformanceSalaryEqualTo(Float value) {
            addCriterion("performance_salary =", value, "performanceSalary");
            return (Criteria) this;
        }

        public Criteria andPerformanceSalaryNotEqualTo(Float value) {
            addCriterion("performance_salary <>", value, "performanceSalary");
            return (Criteria) this;
        }

        public Criteria andPerformanceSalaryGreaterThan(Float value) {
            addCriterion("performance_salary >", value, "performanceSalary");
            return (Criteria) this;
        }

        public Criteria andPerformanceSalaryGreaterThanOrEqualTo(Float value) {
            addCriterion("performance_salary >=", value, "performanceSalary");
            return (Criteria) this;
        }

        public Criteria andPerformanceSalaryLessThan(Float value) {
            addCriterion("performance_salary <", value, "performanceSalary");
            return (Criteria) this;
        }

        public Criteria andPerformanceSalaryLessThanOrEqualTo(Float value) {
            addCriterion("performance_salary <=", value, "performanceSalary");
            return (Criteria) this;
        }

        public Criteria andPerformanceSalaryIn(List<Float> values) {
            addCriterion("performance_salary in", values, "performanceSalary");
            return (Criteria) this;
        }

        public Criteria andPerformanceSalaryNotIn(List<Float> values) {
            addCriterion("performance_salary not in", values, "performanceSalary");
            return (Criteria) this;
        }

        public Criteria andPerformanceSalaryBetween(Float value1, Float value2) {
            addCriterion("performance_salary between", value1, value2, "performanceSalary");
            return (Criteria) this;
        }

        public Criteria andPerformanceSalaryNotBetween(Float value1, Float value2) {
            addCriterion("performance_salary not between", value1, value2, "performanceSalary");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_performance
     *
     * @mbggenerated do_not_delete_during_merge Wed Jan 10 18:43:08 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_performance
     *
     * @mbggenerated Wed Jan 10 18:43:08 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}